#!/bin/bash
## declare an array variable
declare -a arr=(
"Amiri Bold"
"Amiri Bold Italic"
"Amiri"
"Amiri Italic"
"ArabicTypesetting"
"Droid Arabic Naskh"
"Hanzala"
"Lateef"
"Scheherazade"
"Simplified Arabic"
"XB Kayhan Bold"
"XB Kayhan Bold Italic"
"XB Kayhan"
"XB Kayhan Italic"
"XB Khoramshahr Bold"
"XB Khoramshahr Bold Italic"
"XB Khoramshahr"
"XB Khoramshahr Italic"
"XB Niloofar Bold"
"XB Niloofar Bold Italic"
"XB Niloofar"
"XB Niloofar Italic"
"XB Riyaz Bold"
"XB Riyaz Bold Italic"
"XB Riyaz"
"XB Riyaz Italic"
"XB Roya Bold"
"XB Roya Bold Italic"
"XB Roya"
"XB Roya Italic"
"XB Shafigh Bold"
"XB Shafigh Bold Italic"
"XB Shafigh"
"XB Shafigh Italic"
"XB Shafigh Kurd Bold"
"XB Shafigh Kurd Bold Italic"
"XB Shafigh Kurd"
"XB Shafigh Kurd Italic"
"XB Shiraz Bold"
"XB Shiraz Bold Italic"
"XB Shiraz"
"XB Shiraz Italic"
"XB Sols Bold"
"XB Sols Bold Italic"
"XB Sols"
"XB Sols Italic"
"XB Tabriz Bold"
"XB Tabriz Bold Italic"
"XB Tabriz"
"XB Tabriz Italic"
"XB Titre"
"XB Yagut Bold"
"XB Yagut Bold Italic"
"XB Yagut"
"XB Yagut Italic"
"XB Yas Bold"
"XB Yas Bold Italic"
"XB Yas"
"XB Yas Italic"
"XB Zar Bold"
"XB Zar Bold Italic"
"XB Zar"
"XB Zar Italic"
"XM Yekan"
"XP Ziba Bold"
"XP Ziba Bold Italic"
"XP Ziba"
"XP Ziba Italic"
)

## now loop through the above array
for i in "${arr[@]}"
do
   echo "$i"
   echo ${$i// /_}
   text2image --text ~/tessscractch/langdata/ara/ara.training_text --outputbase ara.${i// /_}.exp001  --strip_unrenderable_words --leading=32 --xsize=3600 --char_spacing=0.0 --exposure=0  --max_pages=0  --fonts_dir /home/yonetici/.local/share/fonts  --font  "$i"
   tesseract ara.${i// /_}.exp001.tif ara.${i// /_}.exp001 --psm 6 lstm.train
   # or do whatever with individual element of the array
done

# You can access them using echo "${arr[0]}", "${arr[1]}" also
